#!/bin/bash

set -e
source settings
here=$(pwd)
name="$1"

if [ -z "$name" ]
then
  name="./res/res"
fi
echo "running simulation using name: $name."

rm -f "$name"*.obj
rm -f "$name"*.x


python main.py \
  --out "$name" \
  --procs 6 \
  --vnum 1000000 \
  --nearl 0.0028 \
  --farl 0.035 \
  --stp 1.0e-7 \
  --attract 0.2 \
  --reject 1.0 \
  --unfold 0.1 \
  --triangle 0.1 \
  --stat 10 \
  --obj ./data/base.obj \


#usage: main.py [-h] [--obj OBJ] [--procs PROCS] [--profile PROFILE]
               #[--nearl NEARL] [--farl FARL] [--stp STP] [--reject REJECT]
               #[--attract ATTRACT] [--unfold UNFOLD] [--nmax NMAX] [--itt ITT]
               #[--stat STAT] [--export EXPORT] [--out OUT] [--scale SCALE]

#optional arguments:
  #-h, --help         show this help message and exit
  #--obj OBJ
  #--procs PROCS      number of processors.
  #--profile PROFILE  run in profiler mode?
  #--nearl NEARL
  #--farl FARL
  #--stp STP
  #--reject REJECT
  #--attract ATTRACT
  #--unfold UNFOLD
  #--triangle TRIANGLE
  #--nmax NMAX
  #--itt ITT
  #--stat STAT
  #--export EXPORT
  #--out OUT
  #--scale SCALE

