#!/bin/bash

set -e
source settings
here=$(pwd)

pyx=$(shell find ./src -iname "*.pyx"| sort)

rm -f src/*.html src/*.c
rm -f *.so
rm -f *.pyc
rm -rf build
rm -rf modules/*.pyc

python setup.py build_ext --inplace
cython -a "$pyx"

