#!/bin/bash

set -e
source settings
here=$(pwd)
name="$1"
run_script="$here/make_sphere_scene.py"

if [ -z "$name" ]
then
  echo "you must specify an obj file."
  exit
fi
echo "constructing scene name: $name."


"$blender"  "$here/data/scene.blend" -b -P "$run_script" -- "$name"

