#!/bin/bash

set -e
source settings
here=$(pwd)
name="$1"

if [ -z "$name" ]
then
  name=res
fi
echo "running simulation using name: $name."


rm -f ./res/"$name"*.obj
rm -f ./res/"$name"*.x

python main.py --fn $name --procs 6

