#!/bin/bash

set -e
source settings
here=$(pwd)

rm -f src/*.html src/*.c
rm -f *.so
rm -f *.pyc
rm -rf build
rm -rf modules/*.pyc

echo "asdf"

python setup.py build_ext --inplace

find ./src -iname "*.pyx" | xargs cython -a

