#!/bin/bash

set -e
source settings
here=$(pwd)
name="$1"

if [ -z "$name" ]
then
  name=res
fi
echo "running simulation using name: $name."


rm -f ./res/"$name"*.obj

python main_sources.py "$name"

